"""empty message

Revision ID: 49aae57dc631
Revises: 9820931d00cc
Create Date: 2023-12-12 15:36:58.438019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49aae57dc631'
down_revision = '9820931d00cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('test', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'test', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='unique')
    op.drop_column('test', 'phone_number')
    op.drop_column('test', 'email')
    # ### end Alembic commands ###
