"""empty message

Revision ID: 9820931d00cc
Revises: 2b43f1fc617c
Create Date: 2023-12-12 15:32:08.995776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9820931d00cc'
down_revision = '2b43f1fc617c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('status', sa.String(length=13), nullable=True))
    op.add_column('test', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('test', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'updated_at')
    op.drop_column('test', 'created_at')
    op.drop_column('test', 'status')
    # ### end Alembic commands ###
